Description: Example of a RDS database cluster running in a VPC and a custom deploy process to create tables and users
Transform: "AWS::Serverless-2016-10-31"

Globals:
  Function:
    Runtime: go1.x

Parameters:
  DatabaseName:
    Type: String
    Default: testdatabase
  DatabaseTableName:
    Type: String
    Default: transactions
  RDSDatabaseUserName:
    Type: String
    Default: lambda_user
  RDSDatabaseUserPassword:
    NoEcho: true
    Type: String
    Default: testing1

Resources:
##
#  VPC Related Resources
##
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.1.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: name
        Value:  !Join ['', [!Ref DatabaseName, "-VPC" ]]   
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: VPC
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # Public Subnets
  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.1.10.0/24
      AvailabilityZone: !Select [ 0, !GetAZs ]
      Tags:
      - Key: Names
        Value: !Sub ${DatabaseName}-PublicA
  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.1.20.0/24
      AvailabilityZone: !Select [ 1, !GetAZs ]
      Tags:
      - Key: Names
        Value: !Sub ${DatabaseName}-PublicA

  # Some route tables
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  # Attach the public subnets to public route tables,
  # and attach the private subnets to private route tables:
  PublicSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetA
      RouteTableId: !Ref PublicRouteTable

  PublicSubnetBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetB
      RouteTableId: !Ref PublicRouteTable

##
#  Security Groups Section
##

  # Security Groups
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId: !Ref VPC
      # SecurityGroupIngress:
      # Let's try without this and see if I can still route to the lambda function in the GW
      # - IpProtocol: tcp
      #   FromPort: 80
      #   ToPort: 80
      #   CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: '-1'
        FromPort: -1
        ToPort: -1
        CidrIp: 0.0.0.0/0

  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    DependsOn:
      - PublicSubnetA
      - PublicSubnetB
    Properties:
      GroupDescription: Allow http to client host
      VpcId: !Ref VPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        CidrIp: 69.251.135.83/32
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        CidrIp: 108.56.183.61/32
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        SourceSecurityGroupId: !GetAtt LambdaSecurityGroup.GroupId
      SecurityGroupEgress:
      - IpProtocol: "-1"
        FromPort: -1
        ToPort: -1
        CidrIp: 0.0.0.0/0

  # Subnet Group
  PublicSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupName: publicsubnetgroup
      DBSubnetGroupDescription: Public Subnet Groups
      SubnetIds:
        - !Ref PublicSubnetA
        - !Ref PublicSubnetB

  # Database Cluster (Currently a serverless Aurora SQL DB)
  # I'm not setting Redundancy for this as it's just a test, and EC2 is expensive
  RDSDatabase:
    Type: AWS::RDS::DBCluster
    Properties:
      DBClusterIdentifier: !Ref DatabaseName
      Engine: aurora
      EnableIAMDatabaseAuthentication: true
      MasterUsername: admin
      MasterUserPassword: !Ref RDSDatabaseUserPassword
      DBSubnetGroupName: !Ref PublicSubnetGroup
      VpcSecurityGroupIds:
        - !GetAtt DatabaseSecurityGroup.GroupId
  RDSInstance1:
    Type: AWS::RDS::DBInstance
    DependsOn:
      - PublicSubnetA
    Properties:
      DBClusterIdentifier: !Ref RDSDatabase
      # Customize this to the size machine you want
      DBInstanceClass: db.r4.large
      Engine: aurora
      PubliclyAccessible: true
      DBSubnetGroupName: !Ref PublicSubnetGroup

Outputs:
  VPCID:
    Description: The Logical ID for the VPC
    Value: !Ref VPC
    Export:
      Name: VPCID
  PublicSubnetA:
    Description: The ID for Public Subnet A
    Value: !Ref PublicSubnetA
    Export:
      Name: PublicSubnetA
  PublicSubnetB:
    Description: The ID for Public Subnet B
    Value: !Ref PublicSubnetB
    Export:
      Name: PublicSubnetB
  LambdaSecurityGroupId:
    Description: The Security Group to put on the lambdas that need DB Access
    Value: !GetAtt LambdaSecurityGroup.GroupId
    Export:
      Name: LambdaSecurityGroupId
  RDSDatabaseName:
    Description: Database Name
    Value: !Ref DatabaseName
    Export:
      Name: RDSDatabaseName
  RDSDatabaseTableName:
    Description: Database Table Name
    Value: !Ref DatabaseTableName
    Export:
      Name: RDSDatabaseTableName
  RDSDatabaseUserName:
    Description: Database Service User Name
    Value: !Ref RDSDatabaseUserName
    Export:
      Name: RDSDatabaseUserName
  RDSDatabaseReadHost:
    Description: Database Host URL
    Value: !GetAtt RDSDatabase.ReadEndpoint.Address
    Export:
      Name: RDSDatabaseReadHost